[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["backend", "database", "entities", "matplotlib", "numpy", "pages", "windows"]

[tool.flake8]
max-line-length = 79
max-complexity = 10
